/**
 * The enforcement boundary: a CI check that consumes `ai-sdlc status`'s exit
 * code, so approval stops being a claim the pipeline makes about itself.
 *
 * Provider-neutral on purpose. Claude and Codex adapters describe what a *role*
 * may do; this describes what may enter the repository, which is true regardless
 * of which agent wrote the code or whether an agent wrote it at all. Keeping it
 * out of the adapters preserves the line: agents describe roles, lowering
 * describes provider capability, enforcement sits outside both.
 *
 * What this proves, exactly:
 *
 *   No PR can pass the approval gate unless it identifies an approved epic.
 *
 * Not "the code implements that epic". The association is author-supplied, so a
 * developer or agent can point a PR at any approved epic. Verifying that the
 * diff actually delivers the acceptance criteria is human review's job, and no
 * exit code substitutes for it. Claim what the mechanism enforces, no more.
 */

/** The PR-body marker that names the epic under implementation. */
export const EPIC_MARKER = 'AI-SDLC-Epic';

/**
 * Matches the marker anywhere in the body, on its own line.
 *
 * Multiline rather than anchored at the start: contributors put it under a
 * heading or after the description, and a gate that fails on placement teaches
 * people to distrust the gate rather than to read it. Case-insensitive for the
 * same reason. The id shape is deliberately strict so a typo fails closed
 * instead of resolving to some other epic.
 */
const MARKER_RE = /^[ \t>*-]*AI-SDLC-Epic[ \t]*:[ \t]*([A-Za-z][A-Za-z0-9_]*-\d+)[ \t]*$/im;

export type MarkerResult =
  | { ok: true; id: string }
  | { ok: false; reason: 'absent' | 'malformed' };

/**
 * Extracts the epic id from a PR body.
 *
 * Fails closed in both directions. An absent marker is a failure, not a skip:
 * "no marker means no gate" would make the gate opt-in by omission, which is
 * the fail-open behaviour the whole check exists to remove. A present but
 * unparseable marker is reported separately so the error message can say which
 * mistake was made -- `Epic: 1` and no marker at all deserve different advice.
 */
export function extractEpicId(body: string | undefined | null): MarkerResult {
  if (!body) return { ok: false, reason: 'absent' };
  const match = MARKER_RE.exec(body);
  if (match?.[1]) return { ok: true, id: match[1].toUpperCase() };
  // Distinguish "forgot it" from "got it wrong" by looking for the bare key.
  const mentioned = new RegExp(`${EPIC_MARKER}[ \\t]*:`, 'i').test(body);
  return { ok: false, reason: mentioned ? 'malformed' : 'absent' };
}

/** Human-facing explanation of a failed extraction, printed by the CI step. */
export function markerFailure(reason: 'absent' | 'malformed'): string {
  const example = `${EPIC_MARKER}: EPIC-123`;
  return reason === 'absent'
    ? `No ${EPIC_MARKER} marker in the pull request body.\n\n` +
        `Add a line naming the approved epic this change implements:\n\n    ${example}\n\n` +
        'This check fails closed: an unmarked pull request is not an exempt one.'
    : `Found a ${EPIC_MARKER} line, but could not read an epic id from it.\n\n` +
        `Expected the form:\n\n    ${example}\n\n` +
        'A malformed id fails rather than being guessed at, so a typo cannot resolve to a different epic.';
}

export interface CiWorkflowOptions {
  /** Node version for the setup step. Pinned by the caller, not guessed here. */
  node?: string;
  /** Branches whose pull requests are gated. */
  branches?: string[];
}

/**
 * Emits the GitHub Actions workflow that runs the gate.
 *
 * Returns a file rather than writing one, matching `generateContracts`: the
 * generators stay pure and the CLI owns the filesystem.
 *
 * GitHub-specific by necessity -- "pull request body" is not a neutral concept,
 * and pretending otherwise would mean inventing an abstraction over one
 * implementation. The neutral part is `extractEpicId` and the delegation to
 * `ai-sdlc status`; a GitLab or Gitea emitter would reuse both and replace only
 * this string.
 */
export function generateCiWorkflow(options: CiWorkflowOptions = {}): { path: string; content: string } {
  const node = options.node ?? '20';
  const branches = options.branches ?? ['main'];
  const content = `# Generated by ai-sdlc. Do not edit directly; re-run \`ai-sdlc generate\`.
#
# Proves one property: no pull request passes this check unless it identifies an
# epic that a human has approved. It does not verify that the diff implements
# that epic -- the association is author-supplied. That remains review's job.
name: approval gate

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
${branches.map((b) => `      - ${b}`).join('\n')}

# The body is read from the event payload, so re-running after an edit is what
# picks up a corrected marker. Read-only: this job decides, it does not write.
permissions:
  contents: read

jobs:
  approved-epic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${node}'
      - run: npm ci
      - run: npm run build

      # Passed through the environment rather than interpolated into the script:
      # a PR body is untrusted input, and \`\${{ }}\` in a run block is an
      # injection site.
      - name: Check the epic is approved
        env:
          PR_BODY: \${{ github.event.pull_request.body }}
        run: node dist/enforcement/gate.js
`;
  return { path: '.github/workflows/approval-gate.yml', content };
}
