/**
 * Emits the provider-native repo-instruction files from one neutral contract.
 *
 * Generated rather than symlinked on purpose: symlinks survive a normal clone
 * but not every plugin marketplace fetch or Windows CI checkout, and a contract
 * file that fails to resolve degrades silently — the agent simply behaves as if
 * the project had no conventions.
 */

const BANNER =
  '<!-- Generated by ai-sdlc from .ai/contract.md. Do not edit directly; edit the source and re-run `ai-sdlc generate`. -->';

export type ContractTarget = { path: string; content: string };

export function generateContracts(contract: string): ContractTarget[] {
  const body = `${BANNER}\n\n${contract.trim()}\n`;
  return [
    { path: 'CLAUDE.md', content: body },
    { path: 'AGENTS.md', content: body },
  ];
}
